akshitbatra@Blazer django-blog % python3 manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 03, 2021 - 02:41:29
Django version 3.1.4, using settings 'django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Jan/2021 02:41:36] "GET /admin/auth/user/ HTTP/1.1" 200 7835
[03/Jan/2021 02:41:36] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /admin/jsi18n/ HTTP/1.1" 200 3187
[03/Jan/2021 02:41:36] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/img/search.svg HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[03/Jan/2021 02:41:36] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
[03/Jan/2021 02:41:37] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[03/Jan/2021 02:41:37] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[03/Jan/2021 02:41:37] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
Not Found: /favicon.ico
[03/Jan/2021 02:41:37] "GET /favicon.ico HTTP/1.1" 404 2317
/Users/akshitbatra/projects/django-blog/blog/models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/akshitbatra/projects/django-blog/blog/models.py", line 4
    
    ^
SyntaxError: unexpected EOF while parsing
/Users/akshitbatra/projects/django-blog/blog/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 03, 2021 - 02:42:49
Django version 3.1.4, using settings 'django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/Users/akshitbatra/projects/django-blog/blog/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 03, 2021 - 02:44:27
Django version 3.1.4, using settings 'django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/Users/akshitbatra/projects/django-blog/blog/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 03, 2021 - 02:44:46
Django version 3.1.4, using settings 'django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/Users/akshitbatra/projects/django-blog/blog/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 03, 2021 - 02:45:14
Django version 3.1.4, using settings 'django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/Users/akshitbatra/projects/django-blog/blog/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 03, 2021 - 02:46:04
Django version 3.1.4, using settings 'django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^C%                                                       
akshitbatra@Blazer django-blog % python3 manage.py makemigrations
Migrations for 'blog':
  blog/migrations/0001_initial.py
    - Create model Post
akshitbatra@Blazer django-blog % python3 manage.py migrate 
Operations to perform:
  Apply all migrations: admin, auth, blog, contenttypes, sessions
Running migrations:
  Applying blog.0001_initial... OK
akshitbatra@Blazer django-blog % python3 manage.py sqlmigrate blog 0001
BEGIN;
--
-- Create model Post
--
CREATE TABLE "blog_post" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(100) NOT NULL, "content" text NOT NULL, "date_posted" datetime NOT NULL, "author_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "blog_post_author_id_dd7a8485" ON "blog_post" ("author_id");
COMMIT;
akshitbatra@Blazer django-blog % python3 manage.py shell Python 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from blog.models import Post                      

In [2]: from django.contrib.auth.models import User       

In [3]: User.objects.all()                                
Out[3]: <QuerySet [<User: akshit>]>

In [4]:  User.objects.first()                             
Out[4]: <User: akshit>

In [5]: user =  User.objects.first()                      

In [6]: user                                              
Out[6]: <User: akshit>

In [7]: user.id                                           
Out[7]: 1

In [8]: user.pk                                           
Out[8]: 1

In [9]: Post.objects.all()                                
Out[9]: <QuerySet []>

In [10]: post_1 = Post(title='blog one' content='First pos
    ...: t content' author=user)                          
  File "<ipython-input-10-418f8b3e9051>", line 1
    post_1 = Post(title='blog one' content='First post content' author=user)
                                   ^
SyntaxError: invalid syntax


In [11]:  post_1 = Post(title='blog one', content='first p
    ...: ost content', author=user)                       

In [12]: post_1.save()                                    

In [13]: Post.objects.all()                               
Out[13]: <QuerySet [<Post: Post object (1)>]>

In [14]: post_1.id                                        
Out[14]: 1

In [15]: post_1.title                                     
Out[15]: 'blog one'

In [16]: exit                                             
akshitbatra@Blazer django-blog % python3 manage.py shellPython 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from blog.models import Post                      

In [2]: Post.objects.all()                                
Out[2]: <QuerySet [<Post: blog one>]>

In [3]: from django.contrib.auth.models import User       

In [4]: user = User.objects.first()                       

In [5]: user.email                                        
Out[5]: 'hab2997@gmail.com'

In [6]: post = Post(title='blog two', content='second blog
   ...:  content', author=user).save()                    

In [7]: post                                              

In [8]: post                                              

In [9]: Post.objects.all()                                
Out[9]: <QuerySet [<Post: blog one>, <Post: blog two>]>

In [10]: post = Post.objects.first()                      

In [11]: post.date_posted                                 
Out[11]: datetime.datetime(2021, 1, 3, 3, 28, 32, 625251, tzinfo=<UTC>)

In [12]: post.author                                      
Out[12]: <User: akshit>

In [13]: post.author.email                                
Out[13]: 'hab2997@gmail.com'

In [14]: user.post_set                                    
Out[14]: <django.db.models.fields.related_descriptors.create_reverse_many_to_one_manager.<locals>.RelatedManager at 0x7fed2049c520>

In [15]: user.post_set.all()                              
Out[15]: <QuerySet [<Post: blog one>, <Post: blog two>]>

In [16]: user.post_set.first()                            
Out[16]: <Post: blog one>

In [17]: user.post_set.last()                             
Out[17]: <Post: blog two>

In [18]: user.post_set.create(title='blog 3', content='con
    ...: etnt of blogn three')                            
Out[18]: <Post: blog 3>

In [19]:                                                  